name: .NET

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: ["6.0.x"]
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src -c Release --no-restore
